[env:esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.13/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
lib_deps = bblanchon/ArduinoJson@^7.0.4

[env:native]
platform = native
framework =
build_flags = -std=gnu++17 -DNATIVE_TEST
lib_deps =
    bblanchon/ArduinoJson@^7.0.4
    throwtheswitch/Unity@^2.6.1
lib_compat_mode = off
test_build_src = false
